spring:
  application:
    name: cloudstorage

  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_db
    username: cloud
    password: cloud
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

server:
  port: 8080

storage:
  path: ./uploads

logging:
  level:
    org.springframework.security: TRACE
